name: Docathon Labels Sync

on:
  pull_request_target:
    types: [opened, synchronize, edited]
    branches: [main]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install requests==2.32.3
          pip install PyGithub==2.3.0
      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./.github/scripts/docathon-label-sync.py ${{ github.event.pull_request.number }}
